const {SlashCommandBuilder,ActionRowBuilder,ButtonBuilder,ButtonStyle}=require('discord.js');const {painel,erro,nivelLoja}=require('../../embeds');const {ler,temPermissao,calcularNivelLoja,verificarConquistas}=require('../../banco');
module.exports={data:new SlashCommandBuilder().setName('painel').setDescription('⚙️ Painel ADM'),
async execute(c,i){const D=process.env.DONO_ID||'';const P=(D&&i.user.id===D)||temPermissao(i.user.id,'produtos');
if(!P)return i.reply({embeds:[erro('ACESSO NEGADO','Seu ID: `'+i.user.id+'`')],ephemeral:true});
const v=verificarConquistas();const peds=ler('pedidos')||[];const prods=ler('produtos')||[];const ent=peds.filter(x=>x.status==='ENTREGUE');const avs=ler('avaliacoes')||[];
const r=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_produtos').setLabel('📦 Produtos').setStyle(2),new ButtonBuilder().setCustomId('adm_pedidos').setLabel('📋 Pedidos').setStyle(2),new ButtonBuilder().setCustomId('adm_pagamentos').setLabel('💳 Pagamentos').setStyle(2),new ButtonBuilder().setCustomId('adm_entregas').setLabel('🚚 Entregas').setStyle(2));
const r2=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_cupons').setLabel('🎟️ Cupons').setStyle(2),new ButtonBuilder().setCustomId('adm_carteira').setLabel('💵 Carteira').setStyle(2),new ButtonBuilder().setCustomId('adm_sorteio').setLabel('🎁 Sorteio').setStyle(2),new ButtonBuilder().setCustomId('adm_config').setLabel('⚙️ Config').setStyle(3));
const r3=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('adm_nivel').setLabel('📊 Nivel Loja').setStyle(1),new ButtonBuilder().setCustomId('adm_ranking').setLabel('🏅 Ranking').setStyle(1),new ButtonBuilder().setCustomId('adm_voz').setLabel('🔊 Voz').setStyle(1),new ButtonBuilder().setCustomId('adm_estoque').setLabel('📦 Estoque').setStyle(1));
const s={pedidos:peds.length,entregues:ent.length,faturamento:ent.reduce((s,x)=>s+x.valor,0),produtos:prods.length,clientes:new Set(peds.map(x=>x.clienteId)).size,avaliacao:avs.length?(avs.reduce((s,x)=>s+x.nota,0)/avs.length).toFixed(1):'5.0'};
await i.reply({embeds:[painel(s),nivelLoja(v.res,v.loja)],components:[r,r2,r3],ephemeral:true})}};
