const {ler,salvar,gerarId,addLog}=require('../../banco');
const {sucesso,erro}=require('../../embeds');
const TIPOS=['codigo','cargo','arquivo','link','mensagem','msg','automatica'];
module.exports={id:'modal_produto_criar',async execute(c,i){try{
const g=k=>i.fields.getTextInputValue(k).trim();
const nome=g('nome');const desc=g('descricao');
const preco=parseFloat(g('preco').replace(',','.').replace(/[^0-9.]/g,''));
const estoque=parseInt(g('estoque'))||0;
const extra=g('tipo').split('|').map(x=>x.trim());
const tipo=(extra[0]||'codigo').toLowerCase();
const categoria=(extra[1]||'GERAL').toUpperCase();
const imagem=extra[2]&&extra[2].startsWith('http')?extra[2]:null;
const destaque=(extra[3]||'nao').toUpperCase()==='SIM';
if(!nome||nome.length<3)throw new Error('Nome muito curto');
if(isNaN(preco)||preco<=0)throw new Error('Preco invalido');
const p=ler('produtos')||[];
p.unshift({id:gerarId(),nome,descricao:desc,preco,estoque,tipoEntrega:TIPOS.includes(tipo)?tipo:'codigo',categoria,imagem,destaque,vendas:0,avaliacao:'5.0',dataCriacao:new Date().toISOString()});
salvar('produtos',p);addLog('alteracoes',{acao:'PRODUTO_CRIADO',nome,preco,categoria});
const e=sucesso('✅ PRODUTO CRIADO COM SUCESSO!','**'+nome+'**\nR$ '+preco.toFixed(2)+'\nCategoria: `'+categoria+'`\nEstoque: '+(estoque===-1?'♾️ Ilimitado':estoque)+'\nTipo: `'+tipo+'`'+(imagem?'\n\n🖼️ **FOTO ADICIONADA!**':'')+(destaque?'\n⭐ **EM DESTAQUE NA LOJA!**':''));
if(imagem)e.setImage(imagem);
await i.reply({embeds:[e],ephemeral:true});
}catch(e){await i.reply({embeds:[erro('ERRO AO CRIAR',e.message)],ephemeral:true})}}};
