const {ler,salvar,gerarId,addLog}=require('../../banco');const {sucesso,erro}=require('../../embeds');
const TIPOS=['codigo','cargo','arquivo','link','mensagem','automatica'];
const TAGS=['MAIS_VENDIDO','NOVO','PROMOCAO','LIMITADO'];
module.exports={id:'modal_produto_criar',async execute(c,i){try{
const g=k=>i.fields.getTextInputValue(k).trim();
const nome=g('nome');const desc=g('descricao');
const preco=parseFloat(g('preco').replace(',','.').replace(/[^0-9.]/g,''));
const estoque=parseInt(g('estoque'))||0;
const extra=g('extra').split('|').map(x=>x.trim());
const tipo=(extra[0]||'codigo').toLowerCase();
const categoria=(extra[1]||'GERAL').toUpperCase();
const imagem=extra[2]&&extra[2].startsWith('http')?extra[2]:null;
const video=extra[3]&&extra[3].startsWith('http')?extra[3]:null;
const tag=TAGS.includes((extra[4]||'').toUpperCase())?(extra[4]||'').toUpperCase():null;
const destaque=(extra[5]||'nao').toUpperCase()==='SIM';
const beneficios=extra[6]?extra[6].split(';;;').map(x=>x.trim()).filter(Boolean):null;
if(!nome||nome.length<3)throw new Error('Nome muito curto');
if(isNaN(preco)||preco<=0)throw new Error('Preco invalido');
const p=ler('produtos')||[];
p.unshift({id:gerarId(),nome,descricao:desc,preco,estoque,tipoEntrega:TIPOS.includes(tipo)?tipo:'codigo',categoria,imagem,video,videoTitulo:video?'Assistir demonstracao':null,tag,destaque,beneficios,vendas:0,avaliacao:'5.0',dataCriacao:new Date().toISOString()});
salvar('produtos',p);addLog('alteracoes',{acao:'PRODUTO_CRIADO',nome,preco,categoria});
const e=sucesso('✅ PRODUTO CRIADO COM SUCESSO!','**'+nome+'**\nR$ '+preco.toFixed(2).replace('.',',')+'\nCategoria: `'+categoria+'`\nEstoque: '+(estoque===-1?'♾️ Ilimitado':estoque)+'\nTipo: `'+tipo+'`'+(imagem?'\n\n🖼️ **FOTO ADICIONADA!**':'')+(video?'\n🎬 **VIDEO DEMO ADICIONADO!**':'')+(tag?'\n🏷️ **TAG: '+tag+'**':'')+(destaque?'\n⭐ **EM DESTAQUE NA LOJA!**':'')+(beneficios?'\n✅ **'+beneficios.length+' BENEFICIOS**':''));
if(imagem)e.setImage(imagem);
await i.reply({embeds:[e],ephemeral:true});
}catch(e){await i.reply({embeds:[erro('ERRO AO CRIAR',e.message)],ephemeral:true})}}};
